---
name: neo4j-adapter

releases:
- name: neo4j-adapter
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: neo4j-adapter
  azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: neo4j-adapter
    release: neo4j-adapter
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
